### PR TITLE
Fix urllib import to fix crash on SETDESC - fixes #1

### LINKED ISSUE #1: trezor-gpg-pinentry-tk exits on SETDESC command
When SETDESC command is called, trezor-gpg-pinentry-tk exits from some reason:
```
$ trezor-gpg-pinentry-tk
OK
SETTITLE aaa
OK
SETDESC bbb
$ echo $?
0
```
This prevents trezor-agent to use it:
```
  File "/usr/local/lib/python3.9/site-packages/libagent/device/ui.py", line 42, in get_pin
    return interact(
  File "/usr/local/lib/python3.9/site-packages/libagent/device/ui.py", line 133, in interact
    expect(p, [b'OK'])
  File "/usr/local/lib/python3.9/site-packages/libagent/device/ui.py", line 113, in expect
    raise UnexpectedError(resp)
libagent.device.ui.UnexpectedError: b''
```

My trezor_gpg_pinentry_tk.py is identical with current master (revision 8755766).

### PR DESCRIPTION
**Pull request by thaarok**
Fixes crash on SETDESC call: issue #1 
```
AttributeError: module 'urllib' has no attribute 'parse'
```

### CODE REVIEW

**Comment by rendaw** [comment]
Thanks!  I must have tested it once, but I wonder how it broke like this. I'll release a new version in a minute.

**Comment by thaarok** [comment]
Thanks for fast merge! :)

**Comment by rendaw** [comment]
Released as 0.0.10

**Comment by rendaw** [comment]
NP :D well trezor gpg unlocking is pretty critical IMO

**Pull request merged**
